dz5
KrisEzh/web-library5 pull request #1
Opened 2021-12-08 11:18 UTC by KrisEzh

2021-12-09 03:11 UTC, madyar997 approved these changes

2021-12-09 03:11 UTC, madyar997 commented on src/main/java/pro/sky/java/course2/weblibrary5/EmployeeController.java
> +        employeeService.add(firstName, lastName);
Не используется возвращаемое значение метода, если оно не нужно лучше метод сделать void, также и в остальных методах сервиса

2021-12-09 03:11 UTC, madyar997 commented on src/main/java/pro/sky/java/course2/weblibrary5/EmployeeService.java
> +    boolean findEmployee(String firstName, String lastName) throws EmployeeNotFoundException;
Не вижу самих классов исключений

2021-12-14 11:42 UTC, madyar997 approved these changes

2021-12-14 11:42 UTC, madyar997 commented on src/main/java/pro/sky/java/course2/weblibrary5/EmployeeController.java
> +    @GetMapping(path = "/add")
path писать не обязательно, если других параметров нет

2021-12-14 11:42 UTC, madyar997 commented on src/main/java/pro/sky/java/course2/weblibrary5/EmployeeController.java
> +    @GetMapping(path = "/get")
полный путь получится /employee/get. не совсем получается подходящий путь для эндпоинта по получению коллекции сотрудников

2021-12-14 11:42 UTC, madyar997 commented on src/main/java/pro/sky/java/course2/weblibrary5/EmployeeServiceImpl.java
> +        employees.put(employee.getFirstName()+employee.getLastName(), employee);
используй containsKey чтоб проверить есть ли сотрудник с таким ключом, если есть то EmployeeExistsException, который как раз не используется сейчас

2021-12-14 11:42 UTC, madyar997 commented on src/main/java/pro/sky/java/course2/weblibrary5/EmployeeServiceImpl.java
> +        employees.remove(employee.getFirstName()+employee.getLastName(), String.valueOf(employee));
также обработать ситуацию когда такого сотрудника нет

2021-12-14 11:42 UTC, madyar997 commented on src/main/java/pro/sky/java/course2/weblibrary5/EmployeeServiceImpl.java
> +        }
Лучше в консоль printLn'ом не писать, наверное после дебага осталась)) Позже будем изучать логгеры, которые выполняет эту функцию

2021-12-14 11:42 UTC, madyar997 commented on src/main/java/pro/sky/java/course2/weblibrary5/EmployeeServiceImpl.java
> +        employees.put(employee.getFirstName()+employee.getLastName(), employee);
ну и message для исключений лучше тоже добавить

2021-12-14 11:42 UTC, madyar997 commented on src/main/java/pro/sky/java/course2/weblibrary5/EmployeeServiceImpl.java
> +        }
Сотрудник должен браться из мапы, сейчас он в методе создается и сразу же возвращается

2021-12-15 13:40 UTC, madyar997 approved these changes

2021-12-18 23:55 UTC, OKrylov approved these changes
Отличная работа! Стримы используются корректно, все задачи выполнены верно. По коду оставил несколько замечаний, просьба обратить на них внимание.
На будущее, каждое новое ДЗ нужно сдавать в виде нового пулл реквеста. Старое ДЗ после проверки мы должны смержить в master, затем создаём новую ветку, в ней делаем ДЗ и создаём новый пулл реквест на сдачу ДЗ

2021-12-18 23:55 UTC, OKrylov commented on src/main/java/pro/sky/java/course2/weblibrary5/DepartmentController.java
> +    public DepartmentController(DepartmentService departmentService) {
Для лучшей читаемости поля отделяют пустой строкой от конструктора
```suggestion
    private final DepartmentServiceImpl departmentService;
    
    public DepartmentController(DepartmentService departmentService) {
```

2021-12-18 23:55 UTC, OKrylov commented on src/main/java/pro/sky/java/course2/weblibrary5/DepartmentController.java
> +    private final DepartmentServiceImpl departmentService;
Мы должны использовать интерфейс сервиса в качестве типа поля, его реализация подцепиться автоматически, поскольку она одна и отмечена аннотацией @Service. Это также поможет избежать приведения типов в конструкторе

2021-12-18 23:55 UTC, OKrylov commented on src/main/java/pro/sky/java/course2/weblibrary5/DepartmentServiceImpl.java
> +        this.employeeService=employeeService;
```suggestion
        this.employeeService = employeeService;
```

2021-12-18 23:55 UTC, OKrylov commented on src/main/java/pro/sky/java/course2/weblibrary5/Employee.java
> +        this.departmentNum = Integer.parseInt(String.valueOf(departmentNum));
Не понятна логика данных преобразований с учётом того, что аргумент конструктора и тип поля одинаковые, являются примитивами. Если бы аргумент или поле были типа Integer, то можно посмотреть в сторону метода `valueOf` у класса Integer, либо просто присвоить одно другому, Java автоматически приводят примитивы к их объектным обвёрткам и наоборот (https://habr.com/ru/post/329498/)

2021-12-18 23:55 UTC, OKrylov commented on src/main/java/pro/sky/java/course2/weblibrary5/Employee.java
> +        return "Employee{" +
как минимум toString есть смысл перегенерировать из-за добавления новых полей, equals и hashCode уже по обстоятельствам

2022-01-09 20:46 UTC, Avenirre approved these changes

2022-01-20 23:21 UTC, OKrylov requested changes
Имеется некоторое недопонимание того, как и когда использовать mock объекты. Я оставил несколько замечаний по коду, просьба обратить на них внимание.
Если будут вопросы - пишите

2022-01-20 23:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/EmployeeServiceTest.java
> +        assertTrue(actual.size()==expected.size() && actual.containsAll(expected) && expected.containsAll(actual));
поскольку коллекции имеют одинаковый тип, можно просто сравнить на equals `assertEquals(expected, actual); `

2022-01-20 23:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/EmployeeServiceTest.java
> +        actual.remove(employee);
мы должны тестировать out объект, без него данный тест просто тестирует jdk коллекции, которые мы не писали, следовательно нет смысла их тестировать

2022-01-20 23:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/EmployeeServiceTest.java
> +    private Employee employee = new Employee("Иван", "Иванов", 1, 10);
вы создаете работников как в полях, так и в "конструкторе" теста, нужно выбрать что-то одно

2022-01-20 23:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/DepartmentServiceTest.java
> +        out = new DepartmentServiceImpl(employeeServiceMock);
все тестируемые методы в итоге вызывают у employee service метод 'getEmployees', значит именно его нам и нужно замокать в виде `when(employeeServiceMock.getEmployees()).thenReturn(Lists.newArrayList(employee, employee1, employee2));`, а остальные методы не трогать

2022-01-20 23:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/DepartmentServiceTest.java
> +        employeeServiceMock.add(employee);
так как это mock, то данный вызов не имеет смысла

2022-01-20 23:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/DepartmentServiceTest.java
> +        assertEquals(MAX_SALARY, out.getMaxSalary(CORRECT_DEPARTMENT).getSalary());
искомая зп не соответствует тому, что мы имеем для 1 отдела, который является искомым

2022-01-20 23:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/DepartmentServiceTest.java
> +        when(out.getEmployeesFor(1)).thenReturn(actual);
оборачивать нужно только Mock объект, out которым не является

2022-01-20 23:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/DepartmentServiceTest.java
> +        when(employeeServiceMock.getEmployees()).thenThrow(EmployeeNotFoundException.class);
данный тест ничего не делает

2022-01-22 00:21 UTC, OKrylov requested changes
В целом уже практически все верно, оставил несколько небольших замечаний

2022-01-22 00:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/DepartmentServiceTest.java
>      @InjectMocks
либо используем аннотацию, либо явно задаем через конструктор как выше

2022-01-22 00:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/DepartmentServiceTest.java
> +        assertEquals(MAX_SALARY, out.getMaxSalary(3).getSalary());
стоит иметь нескольких работников в одном отделе для данного теста

2022-01-22 00:21 UTC, OKrylov commented on src/test/java/pro/sky/java/course2/weblibrary5/DepartmentServiceTest.java
> +        if (employeeService.getEmployees() == null) {
данный тестовый класс для DepartmentService, но он отсутствует в данном методе

2022-04-11 16:26 UTC, merged